"""从 registry.yaml 渲染 gate-checklist.md 的 migration 工具。

设计来源：requirements/REQ-2026-002/artifacts/detailed-design.md §5.3

用法：
  python3 scripts/gates/migration/render-docs.py          # 渲染并写入目标文件
  python3 scripts/gates/migration/render-docs.py --check  # CI 强校验：diff 非空 exit 1

目标文件：.claude/skills/managing-requirement-lifecycle/reference/gate-checklist.md
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

import yaml

_REPO_ROOT = Path(__file__).resolve().parents[3]
_REGISTRY_PATH = _REPO_ROOT / "scripts" / "gates" / "registry.yaml"
_OUTPUT_PATH = (
    _REPO_ROOT
    / ".claude"
    / "skills"
    / "managing-requirement-lifecycle"
    / "reference"
    / "gate-checklist.md"
)

# trigger 展示顺序（按执行频率从高到低）
_TRIGGER_ORDER = [
    "pre-tool-use",
    "pre-commit",
    "phase-transition",
    "submit",
    "ci",
    "post-dev",
]

# severity 排序权重（error 最高优先）
_SEVERITY_ORDER = {"error": 0, "warning": 1, "info": 2}

# trigger 中文描述
_TRIGGER_LABELS = {
    "pre-tool-use": "pre-tool-use（工具调用前）",
    "pre-commit": "pre-commit（提交前）",
    "phase-transition": "phase-transition（阶段切换）",
    "submit": "submit（PR 提交）",
    "ci": "ci（持续集成）",
    "post-dev": "post-dev（开发完成后）",
}


def render_gate_checklist(registry: dict) -> str:
    """从 registry 渲染 gate-checklist.md。

    输出文件头自动加 generated 标记（来源：requirements/REQ-2026-002/plan.md:43）。
    按 trigger 分组，组内按 severity（error > warning > info）排序，
    每个 gate 输出「id (severity) — failure_message 首行」格式。

    参数：registry — 已解析的 registry.yaml dict。
    返回：完整的 Markdown 字符串（不含末尾换行）。
    """
    gates = registry.get("gates", [])

    # 按 trigger 分组，保持每 gate 可出现在多个 trigger 下
    by_trigger: dict[str, list[dict]] = {t: [] for t in _TRIGGER_ORDER}
    for gate in gates:
        for trigger in gate.get("triggers", []):
            if trigger in by_trigger:
                by_trigger[trigger].append(gate)

    lines = [
        "<!-- generated by scripts/gates/migration/render-docs.py, do not edit -->",
        "",
        "# 阶段门禁检查清单",
        "",
        "本文件由 `scripts/gates/migration/render-docs.py` 从 `scripts/gates/registry.yaml` 自动生成。",
        "**请勿手动编辑**——如需修改门禁规则，请更新 registry.yaml 后重新生成。",
        "",
    ]

    for trigger in _TRIGGER_ORDER:
        trigger_gates = by_trigger.get(trigger, [])
        if not trigger_gates:
            continue

        label = _TRIGGER_LABELS.get(trigger, trigger)
        lines.append(f"## {label}")
        lines.append("")

        # 按 severity 排序
        sorted_gates = sorted(
            trigger_gates,
            key=lambda g: _SEVERITY_ORDER.get(g.get("severity", "info"), 99),
        )

        for gate in sorted_gates:
            gate_id = gate.get("id", "<unknown>")
            severity = gate.get("severity", "info")
            failure_msg = gate.get("failure_message", "")
            # 取 failure_message 首行，去掉模板变量占位，简化展示
            first_line = _extract_first_line(failure_msg, gate_id)
            lines.append(f"- [ ] **{gate_id}** (`{severity}`) — {first_line}")

        lines.append("")

    return "\n".join(lines)


def _extract_first_line(failure_message: str, gate_id: str) -> str:
    """提取 failure_message 首行作为摘要。

    去掉 {gate_id} 模板占位符（替换为实际 gate_id），取首行非空内容。
    若 failure_message 为空，返回占位描述。
    """
    if not failure_message:
        return f"{gate_id} 失败"
    # 替换 {gate_id} 占位符
    rendered = failure_message.replace("{gate_id}", gate_id)
    # 取首行（multiline 时仅取第一行）
    first = rendered.splitlines()[0].strip()
    return first or f"{gate_id} 失败"


def _load_registry() -> dict:
    """加载 registry.yaml；解析或读取失败则打 ERROR 后 exit 1。

    返回：已解析的 registry dict（YAML 顶层对象）。
    异常：FileNotFoundError / yaml.YAMLError / OSError 全部捕获，
      转换为 sys.exit(1) + ERROR 日志，让 CI 显示为门禁失败而非脚本崩溃。
    """
    if not _REGISTRY_PATH.exists():
        # 尽量输出相对仓库根的路径，避免 CI 日志泄露宿主机绝对目录
        try:
            _display = _REGISTRY_PATH.relative_to(_REPO_ROOT)
        except ValueError:
            _display = _REGISTRY_PATH
        print(f"ERROR registry.yaml 不存在：{_display}", file=sys.stderr)
        sys.exit(1)
    try:
        with _REGISTRY_PATH.open("r", encoding="utf-8") as f:
            return yaml.safe_load(f) or {}
    except yaml.YAMLError as exc:
        print(f"ERROR registry.yaml 语法错误：{exc}", file=sys.stderr)
        sys.exit(1)
    except OSError as exc:
        print(f"ERROR registry.yaml 读取失败：{exc}", file=sys.stderr)
        sys.exit(1)


def main() -> int:
    """render-docs.py 主入口。

    --check 模式（CI 用）：重新渲染并与现有文件 diff，diff 非空 exit 1。
    默认模式：渲染并写入目标文件，打印写入路径后退 0。
    """
    check_mode = "--check" in sys.argv

    registry = _load_registry()
    rendered = render_gate_checklist(registry)

    if check_mode:
        if not _OUTPUT_PATH.exists():
            print(
                f"ERROR --check 模式：目标文件不存在 {_OUTPUT_PATH}；"
                "请先运行 python3 scripts/gates/migration/render-docs.py 生成",
                file=sys.stderr,
            )
            return 1
        current = _OUTPUT_PATH.read_text(encoding="utf-8")
        if current == rendered:
            print("OK gate-checklist.md 与 registry 同步，无差异")
            return 0
        # 打印差异提示（不打印完整 diff，避免泄露内容）
        current_lines = current.splitlines()
        rendered_lines = rendered.splitlines()
        print(
            f"FAIL gate-checklist.md 与 registry 不同步："
            f"当前 {len(current_lines)} 行，渲染结果 {len(rendered_lines)} 行",
            file=sys.stderr,
        )
        print(
            "修复方式：运行 python3 scripts/gates/migration/render-docs.py 重新生成后提交",
            file=sys.stderr,
        )
        return 1

    # 默认模式：原子写入目标文件（先写 .tmp 再 os.replace，避免中途崩溃留 partial 文件）
    _OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    tmp_path = _OUTPUT_PATH.with_suffix(".md.tmp")
    try:
        tmp_path.write_text(rendered, encoding="utf-8")
        os.replace(tmp_path, _OUTPUT_PATH)
    except OSError as exc:
        # 清理可能遗留的 .tmp 文件
        try:
            tmp_path.unlink(missing_ok=True)
        except OSError:
            pass
        print(f"ERROR gate-checklist.md 写入失败：{exc}", file=sys.stderr)
        return 1
    print(f"OK 渲染完成：{_OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
